<?php
/**
 * MysqlKind
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Upmind\EnhanceSdk\Model;
use \Upmind\EnhanceSdk\ObjectSerializer;

/**
 * MysqlKind Class Doc Comment
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MysqlKind
{
    /**
     * Possible values of this enum
     */
    public const MYSQL80 = 'mysql80';

    public const MYSQL81 = 'mysql81';

    public const MARIA_DB_LTS = 'mariaDbLts';

    public const MARIA_DB11 = 'mariaDb11';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MYSQL80,
            self::MYSQL81,
            self::MARIA_DB_LTS,
            self::MARIA_DB11,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


