<?php
/**
 * WebserverKind
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Upmind\EnhanceSdk\Model;
use \Upmind\EnhanceSdk\ObjectSerializer;

/**
 * WebserverKind Class Doc Comment
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebserverKind
{
    /**
     * Possible values of this enum
     */
    public const LITE_SPEED = 'liteSpeed';

    public const OPEN_LITE_SPEED = 'openLiteSpeed';

    public const DUMMY_WEB_SERVER = 'dummyWebServer';

    public const APACHE = 'apache';

    public const NGINX = 'nginx';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LITE_SPEED,
            self::OPEN_LITE_SPEED,
            self::DUMMY_WEB_SERVER,
            self::APACHE,
            self::NGINX,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}


