<?php
/**
 * CanUseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Upmind\EnhanceSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CanUseTest Class Doc Comment
 *
 * @category    Class
 * @description CanUse
 * @package     Upmind\EnhanceSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CanUseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CanUse"
     */
    public function testCanUse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ftp"
     */
    public function testPropertyFtp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "file_manager"
     */
    public function testPropertyFileManager()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "php_versions"
     */
    public function testPropertyPhpVersions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "redis"
     */
    public function testPropertyRedis()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mod_sec"
     */
    public function testPropertyModSec()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "backup"
     */
    public function testPropertyBackup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mysql_kind"
     */
    public function testPropertyMysqlKind()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
