<?php
/**
 * UpdateImportServerSettingsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Upmind\EnhanceSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateImportServerSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateImportServerSettings
 * @package     Upmind\EnhanceSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateImportServerSettingsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateImportServerSettings"
     */
    public function testUpdateImportServerSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hostname"
     */
    public function testPropertyHostname()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "friendly_name"
     */
    public function testPropertyFriendlyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ssh_user"
     */
    public function testPropertySshUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ssh_public_key"
     */
    public function testPropertySshPublicKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ssh_private_key"
     */
    public function testPropertySshPrivateKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "auth_kind"
     */
    public function testPropertyAuthKind()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "auth_user"
     */
    public function testPropertyAuthUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ssh_port"
     */
    public function testPropertySshPort()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "api_port"
     */
    public function testPropertyApiPort()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allow_partial_sync"
     */
    public function testPropertyAllowPartialSync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "as_user_root"
     */
    public function testPropertyAsUserRoot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
