<?php
/**
 * UpdateEmailTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Upmind\EnhanceSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateEmailTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateEmail
 * @package     Upmind\EnhanceSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateEmailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateEmail"
     */
    public function testUpdateEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mailbox_name"
     */
    public function testPropertyMailboxName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mailbox_password"
     */
    public function testPropertyMailboxPassword()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aliases"
     */
    public function testPropertyAliases()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "forwarders"
     */
    public function testPropertyForwarders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "has_mailbox"
     */
    public function testPropertyHasMailbox()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quota"
     */
    public function testPropertyQuota()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blacklist"
     */
    public function testPropertyBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "whitelist"
     */
    public function testPropertyWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
