<?php
/**
 * EmailsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Upmind\EnhanceSdk\Test\Api;

use \Upmind\EnhanceSdk\Configuration;
use \Upmind\EnhanceSdk\ApiException;
use \Upmind\EnhanceSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EmailsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWebsiteEmail
     *
     * Create an email under website's domain.
     *
     */
    public function testCreateWebsiteEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWebsiteEmailAutoresponder
     *
     * Create new website email autoresponder.
     *
     */
    public function testCreateWebsiteEmailAutoresponder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebsiteEmail
     *
     * Delete website email.
     *
     */
    public function testDeleteWebsiteEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebsiteEmailAutoresponder
     *
     * Delete website email autoresponder.
     *
     */
    public function testDeleteWebsiteEmailAutoresponder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDomainEmailAuth
     *
     * Get email authentication preferences.
     *
     */
    public function testGetDomainEmailAuth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDomainLocalRemote
     *
     * Get the current local/remote status.
     *
     */
    public function testGetDomainLocalRemote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmailSpamThresholds
     *
     * Get spam thresholds for an email address.
     *
     */
    public function testGetEmailSpamThresholds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEmails
     *
     * Get org emails.
     *
     */
    public function testGetEmails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsiteEmail
     *
     * Get website email.
     *
     */
    public function testGetWebsiteEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsiteEmailAutoresponder
     *
     * Get website email autoresponder.
     *
     */
    public function testGetWebsiteEmailAutoresponder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsiteEmailClientConf
     *
     * Get website email client configuration.
     *
     */
    public function testGetWebsiteEmailClientConf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsiteEmails
     *
     * Get website emails.
     *
     */
    public function testGetWebsiteEmails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setDomainLocalRemote
     *
     * Update email local/remote status.
     *
     */
    public function testSetDomainLocalRemote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setEmailSpamThresholds
     *
     * Set spam thresholds for an email address.
     *
     */
    public function testSetEmailSpamThresholds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDomainEmailAuth
     *
     * Update email authentication preferences.
     *
     */
    public function testUpdateDomainEmailAuth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebsiteEmail
     *
     * Update website email.
     *
     */
    public function testUpdateWebsiteEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for validateDomainEmailAuth
     *
     * Validate email authentication DNS records.
     *
     */
    public function testValidateDomainEmailAuth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
