<?php
/**
 * MysqlApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Upmind\EnhanceSdk\Test\Api;

use \Upmind\EnhanceSdk\Configuration;
use \Upmind\EnhanceSdk\ApiException;
use \Upmind\EnhanceSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MysqlApiTest Class Doc Comment
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MysqlApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWebsiteMySQLDB
     *
     * Create a MySQL database for website.
     *
     */
    public function testCreateWebsiteMySQLDB()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWebsiteMySQLUser
     *
     * Create website MySQL database user.
     *
     */
    public function testCreateWebsiteMySQLUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWebsiteMySQLUserAccessHosts
     *
     * Create website MySQL database user access hosts.
     *
     */
    public function testCreateWebsiteMySQLUserAccessHosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebsiteMySQLDB
     *
     * Delete website MySQL database.
     *
     */
    public function testDeleteWebsiteMySQLDB()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebsiteMySQLUser
     *
     * Delete website MySQL database user.
     *
     */
    public function testDeleteWebsiteMySQLUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebsiteMySQLUserAccessHosts
     *
     * Delete website MySQL database user access hosts.
     *
     */
    public function testDeleteWebsiteMySQLUserAccessHosts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadSql
     *
     * Takes a backup of given database and returns it gziped.
     *
     */
    public function testDownloadSql()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPhpMyAdminSSOUrl
     *
     * Get phpMyAdmin SSO URL.
     *
     */
    public function testGetPhpMyAdminSSOUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsiteMySQLDBs
     *
     * Get website MySQL databases.
     *
     */
    public function testGetWebsiteMySQLDBs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsiteMySQLUsers
     *
     * Get website MySQL database users.
     *
     */
    public function testGetWebsiteMySQLUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setWebsiteMySQLUserPrivileges
     *
     * Create website MySQL database user privileges.
     *
     */
    public function testSetWebsiteMySQLUserPrivileges()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebsiteMySQLUser
     *
     * Update website MySQL database user.
     *
     */
    public function testUpdateWebsiteMySQLUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadSql
     *
     * Uploads sql file and executes it against db.
     *
     */
    public function testUploadSql()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
