<?php
/**
 * PostgresqlApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 12.22.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Upmind\EnhanceSdk\Test\Api;

use \Upmind\EnhanceSdk\Configuration;
use \Upmind\EnhanceSdk\ApiException;
use \Upmind\EnhanceSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PostgresqlApiTest Class Doc Comment
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PostgresqlApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWebsitePostgresqlDb
     *
     * Create a PostgreSQL database for website.
     *
     */
    public function testCreateWebsitePostgresqlDb()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWebsitePostgresqlUser
     *
     * Create website PostgreSQL database user.
     *
     */
    public function testCreateWebsitePostgresqlUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebsitePostgresqlDb
     *
     * Delete website PostgreSQL database.
     *
     */
    public function testDeleteWebsitePostgresqlDb()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebsitePostgresqlUser
     *
     * Delete website PostgreSQL database user.
     *
     */
    public function testDeleteWebsitePostgresqlUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsitePostgresqlDbs
     *
     * Get website PostgreSQL databases.
     *
     */
    public function testGetWebsitePostgresqlDbs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsitePostgresqlUsers
     *
     * Get website PostgreSQL database users.
     *
     */
    public function testGetWebsitePostgresqlUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for grantPostgresqlUserDbPrivileges
     *
     * Grant privileges on a specific database.
     *
     */
    public function testGrantPostgresqlUserDbPrivileges()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokePostgresqlUserDbPrivileges
     *
     * Remove privileges on this database.
     *
     */
    public function testRevokePostgresqlUserDbPrivileges()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebsitePostgresqlUser
     *
     * Update website PostgreSQL database user.
     *
     */
    public function testUpdateWebsitePostgresqlUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
