<?php
/**
 * SettingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * orchd
 *
 * orchd API docs
 *
 * The version of the OpenAPI document: 10.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Upmind\EnhanceSdk\Test\Api;

use \Upmind\EnhanceSdk\Configuration;
use \Upmind\EnhanceSdk\ApiException;
use \Upmind\EnhanceSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SettingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Upmind\EnhanceSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SettingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addOrchdLoginPolicyEmailBlacklist
     *
     * Set the orchd login policy email blacklist as a whole.
     *
     */
    public function testAddOrchdLoginPolicyEmailBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addOrchdLoginPolicyEmailWhitelist
     *
     * Set the orchd login policy email whitelist as a whole.
     *
     */
    public function testAddOrchdLoginPolicyEmailWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addOrchdLoginPolicyIpBlacklist
     *
     * Set the orchd login policy ip blacklist as a whole.
     *
     */
    public function testAddOrchdLoginPolicyIpBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addOrchdLoginPolicyIpWhitelist
     *
     * Set the orchd login policy ip whitelist as a whole.
     *
     */
    public function testAddOrchdLoginPolicyIpWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addOrchdLoginPolicySettings
     *
     * Set a single orchd login policy setting.
     *
     */
    public function testAddOrchdLoginPolicySettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createBackupRemoteStorageS3
     *
     * Create S3 object storage settings at platform level..
     *
     */
    public function testCreateBackupRemoteStorageS3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSettings
     *
     * Create settings.
     *
     */
    public function testCreateSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteBackupRemoteStorageS3
     *
     * Delete S3 object storage settings at platform level..
     *
     */
    public function testDeleteBackupRemoteStorageS3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteGlobalServiceSetting
     *
     * Delete a single global service setting.
     *
     */
    public function testDeleteGlobalServiceSetting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrchdLoginPolicyEmailBlacklist
     *
     * Delete an orchd login policy email blacklist.
     *
     */
    public function testDeleteOrchdLoginPolicyEmailBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrchdLoginPolicyEmailWhitelist
     *
     * Delete an orchd login policy email whitelist.
     *
     */
    public function testDeleteOrchdLoginPolicyEmailWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrchdLoginPolicyIpBlacklist
     *
     * Delete an orchd login policy ip blacklist.
     *
     */
    public function testDeleteOrchdLoginPolicyIpBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrchdLoginPolicyIpWhitelist
     *
     * Delete an orchd login policy ip whitelist.
     *
     */
    public function testDeleteOrchdLoginPolicyIpWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSetting
     *
     * Remove the specified setting.
     *
     */
    public function testDeleteSetting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBackupRemoteStorageS3
     *
     * Get S3 object storage settings at platform level..
     *
     */
    public function testGetBackupRemoteStorageS3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDemoMode
     *
     * Get the demo mode status of the orchd service.
     *
     */
    public function testGetDemoMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDockerRegistry
     *
     * Gets the Docker registry credentials..
     *
     */
    public function testGetDockerRegistry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getGlobalServiceSetting
     *
     * Get the value for a particular global service setting.
     *
     */
    public function testGetGlobalServiceSetting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrchdLogSettings
     *
     * Get the orchd log settings.
     *
     */
    public function testGetOrchdLogSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrchdLoginPolicyEmailBlacklist
     *
     * Get the orchd login policy email blacklist.
     *
     */
    public function testGetOrchdLoginPolicyEmailBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrchdLoginPolicyEmailWhitelist
     *
     * Get the orchd login policy email whitelist.
     *
     */
    public function testGetOrchdLoginPolicyEmailWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrchdLoginPolicyIpBlacklist
     *
     * Get the orchd login policy ip blacklist.
     *
     */
    public function testGetOrchdLoginPolicyIpBlacklist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrchdLoginPolicyIpWhitelist
     *
     * Get the orchd login policy ip whitelist.
     *
     */
    public function testGetOrchdLoginPolicyIpWhitelist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrchdLoginPolicySettings
     *
     * Get the orchd login policy settings.
     *
     */
    public function testGetOrchdLoginPolicySettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProhibitedDomains
     *
     * Get the platform level prohibited domains as a newline separated list.
     *
     */
    public function testGetProhibitedDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSetting
     *
     * Get the specified setting.
     *
     */
    public function testGetSetting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSettings
     *
     * Get all current settings.
     *
     */
    public function testGetSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setDockerRegistry
     *
     * Updates the Docker registry credentials..
     *
     */
    public function testSetDockerRegistry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setGlobalServiceSetting
     *
     * Set a single global service setting.
     *
     */
    public function testSetGlobalServiceSetting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setOrchdLogSettings
     *
     * Set the orchd log settings.
     *
     */
    public function testSetOrchdLogSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setProhibitedDomains
     *
     * Set the platform level prohibited domains.
     *
     */
    public function testSetProhibitedDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateBackupRemoteStorageS3
     *
     * Update S3 object storage settings at platform level..
     *
     */
    public function testUpdateBackupRemoteStorageS3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSetting
     *
     * Create or update the specified setting.
     *
     */
    public function testUpdateSetting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
